/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.21
 * Generated at: 2026-04-05 18:51:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>All Registrations</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: Arial, sans-serif; margin: 40px; background: #f0f2f5; }\r\n");
      out.write("        .container { max-width: 850px; margin: auto; background: white;\r\n");
      out.write("                     padding: 30px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }\r\n");
      out.write("        h2 { color: #2c3e50; }\r\n");
      out.write("        table { width: 100%; border-collapse: collapse; margin-top: 15px; }\r\n");
      out.write("        th { background: #2c3e50; color: white; padding: 10px; text-align: left; }\r\n");
      out.write("        td { padding: 10px; border-bottom: 1px solid #ddd; }\r\n");
      out.write("        tr:hover { background: #f5f5f5; }\r\n");
      out.write("        .edit-btn   { padding: 5px 12px; background: #f39c12; color: white;\r\n");
      out.write("                      text-decoration: none; border-radius: 3px; }\r\n");
      out.write("        .delete-btn { padding: 5px 12px; background: #e74c3c; color: white;\r\n");
      out.write("                      text-decoration: none; border-radius: 3px; margin-left: 5px; }\r\n");
      out.write("        a.home { color: #3498db; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h2>All Workshop Registrations</h2>\r\n");
      out.write("\r\n");
      out.write("    ");

        Connection conn = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/workshop_db", "root", "");

            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(
                "SELECT * FROM students ORDER BY registered_at DESC");
    
      out.write("\r\n");
      out.write("    <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>#</th>\r\n");
      out.write("            <th>Name</th>\r\n");
      out.write("            <th>Student ID</th>\r\n");
      out.write("            <th>Workshop</th>\r\n");
      out.write("            <th>Registered At</th>\r\n");
      out.write("            <th>Actions</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");

            int count = 0;
            while (rs.next()) {
                count++;
        
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>");
      out.print( count );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( rs.getString("name") );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( rs.getString("student_id") );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( rs.getString("workshop") );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( rs.getTimestamp("registered_at") );
      out.write("</td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <a class=\"edit-btn\"   href=\"edit.jsp?id=");
      out.print( rs.getInt("id") );
      out.write("\">Edit</a>\r\n");
      out.write("                <a class=\"delete-btn\" href=\"delete.jsp?id=");
      out.print( rs.getInt("id") );
      out.write("\"\r\n");
      out.write("                   onclick=\"return confirm('Delete this registration?')\">Delete</a>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (count == 0) { 
      out.write("\r\n");
      out.write("        <tr><td colspan=\"6\" style=\"text-align:center;\">No registrations found.</td></tr>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("    ");

        } catch (Exception e) { 
      out.write("\r\n");
      out.write("        <p style=\"color:red;\">Error: ");
      out.print( e.getMessage() );
      out.write("</p>\r\n");
      out.write("    ");
 } finally {
        if (conn != null) try { conn.close(); } catch (Exception e) {}
    } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <br><a class=\"home\" href=\"register.jsp\">+ New Registration</a> |\r\n");
      out.write("    <a class=\"home\" href=\"index.jsp\">Home</a>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
