/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.21
 * Generated at: 2026-04-05 18:51:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Register for Workshop</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: Arial, sans-serif; margin: 40px; background: #f0f2f5; }\r\n");
      out.write("        .container { max-width: 500px; margin: auto; background: white;\r\n");
      out.write("                     padding: 30px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }\r\n");
      out.write("        h2 { color: #2c3e50; }\r\n");
      out.write("        label { display: block; margin-top: 15px; font-weight: bold; }\r\n");
      out.write("        input, select { width: 100%; padding: 8px; margin-top: 5px;\r\n");
      out.write("                        border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; }\r\n");
      out.write("        button { margin-top: 20px; padding: 10px 25px; background: #27ae60;\r\n");
      out.write("                 color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; }\r\n");
      out.write("        button:hover { background: #219150; }\r\n");
      out.write("        .error { color: red; margin-top: 10px; }\r\n");
      out.write("        a { color: #3498db; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h2>Student Workshop Registration</h2>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");

        String message = "";
        if ("POST".equalsIgnoreCase(request.getMethod())) {
            String name     = request.getParameter("name");
            String studId   = request.getParameter("student_id");
            String workshop = request.getParameter("workshop");

            if (name != null && !name.trim().isEmpty() &&
                studId != null && !studId.trim().isEmpty() &&
                workshop != null && !workshop.trim().isEmpty()) {

                Connection conn = null;
                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    conn = DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/workshop_db", "root", "");

                    PreparedStatement ps = conn.prepareStatement(
                        "INSERT INTO students (name, student_id, workshop) VALUES (?, ?, ?)");
                    ps.setString(1, name.trim());
                    ps.setString(2, studId.trim());
                    ps.setString(3, workshop);
                    ps.executeUpdate();

                    // Redirect to confirmation page
                    response.sendRedirect("confirmation.jsp?name=" +
                        java.net.URLEncoder.encode(name.trim(), "UTF-8") +
                        "&student_id=" + java.net.URLEncoder.encode(studId.trim(), "UTF-8") +
                        "&workshop=" + java.net.URLEncoder.encode(workshop, "UTF-8"));
                    return;

                } catch (SQLIntegrityConstraintViolationException e) {
                    message = "Error: Student ID already registered!";
                } catch (Exception e) {
                    message = "Database error: " + e.getMessage();
                } finally {
                    if (conn != null) try { conn.close(); } catch (Exception e) {}
                }
            } else {
                message = "All fields are required.";
            }
        }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if (!message.isEmpty()) { 
      out.write("\r\n");
      out.write("        <p class=\"error\">");
      out.print( message );
      out.write("</p>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <form method=\"post\" action=\"register.jsp\">\r\n");
      out.write("        <label>Full Name:</label>\r\n");
      out.write("        <input type=\"text\" name=\"name\" placeholder=\"e.g. Ahmad bin Ali\" required>\r\n");
      out.write("\r\n");
      out.write("        <label>Student ID:</label>\r\n");
      out.write("        <input type=\"text\" name=\"student_id\" placeholder=\"e.g. S12345\" required>\r\n");
      out.write("\r\n");
      out.write("        <label>Select Workshop:</label>\r\n");
      out.write("        <select name=\"workshop\" required>\r\n");
      out.write("            <option value=\"\">-- Choose a Workshop --</option>\r\n");
      out.write("            <option value=\"Web Development\">Web Development</option>\r\n");
      out.write("            <option value=\"Database Management\">Database Management</option>\r\n");
      out.write("            <option value=\"Cybersecurity Basics\">Cybersecurity Basics</option>\r\n");
      out.write("            <option value=\"Python Programming\">Python Programming</option>\r\n");
      out.write("            <option value=\"Cloud Computing\">Cloud Computing</option>\r\n");
      out.write("        </select>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\">Register</button>\r\n");
      out.write("    </form>\r\n");
      out.write("    <br><a href=\"index.jsp\">← Back to Home</a>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
